version: '3.8'
services:
  frontend:
    container_name: frontend
    networks:
      - mywebsite
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
  
  backend:
    container_name: backend
    networks:
      - mywebsite
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'

  nginx:
    container_name: nginx
    networks:
      - mywebsite
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - frontend
      - backend
    ports:
      - '80:80'

networks:
  mywebsite: 

